version: '3.8'

services:
  staff-attendance-app:
    build: .
    container_name: staff-attendance-system
    ports:
      - "8000:8000"   # Django frontend
      - "5600:5600"   # FastAPI backend
    volumes:
      - ./media:/app/media
      - ./logs:/app/logs
      - ./StaffFaceRecognition/db.sqlite3:/app/StaffFaceRecognition/db.sqlite3
      - ./face_embeddings.json:/app/face_embeddings.json
      - ./StaffFaceRecognition/backend/dataset:/app/StaffFaceRecognition/backend/dataset
    environment:
      - PYTHONUNBUFFERED=1
      - IP=127.0.0.1
    devices:
      - /dev/video0:/dev/video0  # Camera access
    stdin_open: true
    tty: true
    restart: unless-stopped
    networks:
      - staff-network

networks:
  staff-network:
    driver: bridge

volumes:
  db_data:
  media_data:
  embeddings_data:
