# Generated by Django 5.1.5 on 2025-02-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_remove_attendance_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='time_in',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='time_out',
        ),
        migrations.AddField(
            model_name='attendance',
            name='time_list',
            field=models.TextField(blank=True, null=True),
        ),
    ]
