# Generated by Django 5.1.6 on 2025-02-06 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_alter_employeeimage_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='updated_at',
        ),
        migrations.DeleteModel(
            name='EmployeeImage',
        ),
    ]
