# Generated by Django 5.1.6 on 2025-02-06 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_employee_created_at_employee_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeimage',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.employee'),
        ),
    ]
